<?php
/**
 * Service: AiInsightsReportExporter
 * Status: Active - Data Analysis Portal (AI Insights export)
 *
 * بيحوّل تقرير AI Insights واحد (result_json) لملف قابل للتحميل بصيغة
 * pdf / docx / xlsx / csv / json / md. مفيش أي محتوى بيتألّف هنا: كل صف
 * مأخوذ حرفيًا من حقول التقرير المخزّن، وبس العناوين والتسميات هي اللي
 * بتتترجم حسب لغة الواجهة.
 *
 *  - pdf: بيعدّي على PdfWriter::writeReport (mPDF، خط Unicode + عربي RTL).
 *  - docx/xlsx/csv/json: جدول مسطّح (القسم / البند / التفاصيل / المستوى)
 *    عن طريق ReportExportWriter — نفس الكاتب اللي بتستخدمه باقي تصديرات البورتال.
 *  - md: Markdown نصي بسيط.
 *
 * @package UIP
 */

namespace App\Services\Export;

use App\Helpers\ReportExportWriter;

class AiInsightsReportExporter
{
    /** format => Content-Type */
    public const FORMATS = [
        'pdf'  => 'application/pdf',
        'docx' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'xlsx' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'csv'  => 'text/csv; charset=UTF-8',
        'json' => 'application/json',
        'md'   => 'text/markdown; charset=UTF-8',
    ];

    private const LABELS = [
        'en' => [
            'title' => 'AI Insights Report', 'generated_by' => 'Generated by', 'generated_at' => 'Generated at',
            'model' => 'Model', 'report_id' => 'Report #', 'section' => 'Section', 'item' => 'Item',
            'details' => 'Details', 'level' => 'Level',
            'summary' => 'Executive Summary', 'insights' => 'Key Insights', 'trends' => 'Trends',
            'correlations' => 'Correlations', 'anomalies' => 'Anomalies', 'risks' => 'Risks',
            'opportunities' => 'Opportunities', 'root_cause_analysis' => 'Root Cause Analysis',
            'kpi_analysis' => 'KPI Analysis', 'recommendations' => 'Recommendations',
            'performance_recommendations' => 'Performance Recommendations',
            'c_summary' => 'Summary', 'c_insight' => 'Insight', 'c_trend' => 'Trend', 'c_description' => 'Description',
            'c_direction' => 'Direction', 'c_correlation' => 'Correlation', 'c_strength' => 'Strength',
            'c_anomaly' => 'Anomaly', 'c_severity' => 'Severity', 'c_risk' => 'Risk', 'c_opportunity' => 'Opportunity',
            'c_impact' => 'Potential impact', 'c_issue' => 'Issue', 'c_cause' => 'Likely cause', 'c_kpi' => 'KPI',
            'c_analysis' => 'Analysis', 'c_recommendation' => 'Recommendation', 'c_perf' => 'Performance recommendation',
            'high' => 'High', 'medium' => 'Medium', 'low' => 'Low', 'strong' => 'Strong', 'moderate' => 'Moderate',
            'weak' => 'Weak', 'up' => 'Up', 'down' => 'Down', 'flat' => 'Flat',
        ],
        'ar' => [
            'title' => 'تقرير رؤى الذكاء الاصطناعي', 'generated_by' => 'تم التوليد بواسطة', 'generated_at' => 'تاريخ التوليد',
            'model' => 'النموذج', 'report_id' => 'رقم التقرير', 'section' => 'القسم', 'item' => 'البند',
            'details' => 'التفاصيل', 'level' => 'المستوى',
            'summary' => 'الملخص التنفيذي', 'insights' => 'رؤى رئيسية', 'trends' => 'الاتجاهات',
            'correlations' => 'الارتباطات', 'anomalies' => 'الحالات الشاذة', 'risks' => 'المخاطر',
            'opportunities' => 'الفرص', 'root_cause_analysis' => 'تحليل السبب الجذري',
            'kpi_analysis' => 'تحليل مؤشرات الأداء', 'recommendations' => 'التوصيات',
            'performance_recommendations' => 'توصيات الأداء',
            'c_summary' => 'الملخص', 'c_insight' => 'الرؤية', 'c_trend' => 'الاتجاه', 'c_description' => 'الوصف',
            'c_direction' => 'المسار', 'c_correlation' => 'الارتباط', 'c_strength' => 'القوة',
            'c_anomaly' => 'الحالة الشاذة', 'c_severity' => 'الشدة', 'c_risk' => 'الخطر', 'c_opportunity' => 'الفرصة',
            'c_impact' => 'الأثر المحتمل', 'c_issue' => 'المشكلة', 'c_cause' => 'السبب المحتمل', 'c_kpi' => 'المؤشر',
            'c_analysis' => 'التحليل', 'c_recommendation' => 'التوصية', 'c_perf' => 'توصية الأداء',
            'high' => 'مرتفع', 'medium' => 'متوسط', 'low' => 'منخفض', 'strong' => 'قوي', 'moderate' => 'متوسط',
            'weak' => 'ضعيف', 'up' => 'صاعد', 'down' => 'هابط', 'flat' => 'مستقر',
        ],
    ];

    public static function supports(string $format): bool
    {
        return isset(self::FORMATS[$format]);
    }

    /**
     * يكتب الملف في مسار مؤقت ويرجّع مساره (الكنترولر بيبعته ويمسحه بعد الإرسال).
     *
     * @param array<string,mixed> $report صف ai_insight_reports (مع generated_by_name)
     */
    public function build(array $report, string $format, string $lang = 'en'): string
    {
        if (!self::supports($format)) {
            throw new \InvalidArgumentException("Unsupported export format [{$format}].");
        }

        $lang = $lang === 'ar' ? 'ar' : 'en';
        $L = self::LABELS[$lang];
        $result = $this->decode($report['result_json'] ?? null);
        $sections = $this->sections($result, $L);
        $title = $L['title'];

        $meta = [
            $L['report_id']    => '#' . (int) ($report['id'] ?? 0),
            $L['generated_by'] => (string) ($report['generated_by_name'] ?? '—'),
            $L['generated_at'] => (string) ($report['created_at'] ?? ''),
        ];
        if (!empty($report['model_used'])) {
            $meta[$L['model']] = (string) $report['model_used'];
        }

        $path = rtrim(sys_get_temp_dir(), '/\\') . DIRECTORY_SEPARATOR . 'ai_insights_' . bin2hex(random_bytes(6)) . '.' . $format;

        match ($format) {
            'pdf' => PdfWriter::writeReport($path, $title, $meta, $this->pdfSections($sections), null),
            'md'  => $this->writeMarkdown($path, $title, $meta, $sections),
            default => $this->writeFlat($format, $path, $title, $sections, $L),
        };

        if (!is_file($path)) {
            throw new \RuntimeException('Could not write the AI Insights export file.');
        }

        return $path;
    }

    // ------------------------------------------------------------------
    //  Sections (built only from the stored report's own fields)
    // ------------------------------------------------------------------

    /** @return array<string,mixed> */
    private function decode(?string $json): array
    {
        if (!$json) {
            return [];
        }
        $decoded = json_decode($json, true);
        return is_array($decoded) ? $decoded : [];
    }

    /** أي قيمة (نص / array) لنص قابل للطباعة. */
    private function text(mixed $v): string
    {
        if ($v === null) {
            return '';
        }
        if (is_scalar($v)) {
            return trim((string) $v);
        }
        if (is_array($v)) {
            foreach (['description', 'text', 'title'] as $k) {
                if (isset($v[$k]) && is_scalar($v[$k])) {
                    return trim((string) $v[$k]);
                }
            }
            return trim((string) json_encode($v, JSON_UNESCAPED_UNICODE));
        }
        return '';
    }

    private function level(mixed $v, array $L): string
    {
        $raw = $this->text($v);
        $key = strtolower($raw);
        return $L[$key] ?? $raw;
    }

    /**
     * @param array<string,mixed> $result
     * @param array<string,string> $L
     * @return array<int,array{title:string,columns:string[],items:array<int,array{0:string,1:string,2:string}>,paragraph:bool}>
     *         كل item = [البند, التفاصيل, المستوى]
     */
    private function sections(array $result, array $L): array
    {
        $list = fn (string $k): array => is_array($result[$k] ?? null) ? array_values($result[$k]) : [];
        $get = fn (mixed $row, string $k): mixed => is_array($row) ? ($row[$k] ?? null) : null;
        $out = [];
        $push = function (string $title, array $columns, array $items, bool $paragraph = false) use (&$out): void {
            if ($items) {
                $out[] = ['title' => $title, 'columns' => $columns, 'items' => $items, 'paragraph' => $paragraph];
            }
        };

        $summary = $this->text($result['executive_summary'] ?? '');
        $push($L['summary'], ['', $L['c_summary'], ''], $summary !== '' ? [['', $summary, '']] : [], true);

        $push($L['insights'], ['', $L['c_insight'], ''],
            array_map(fn ($r) => ['', $this->text($r), ''], $list('insights')));

        $push($L['trends'], [$L['c_trend'], $L['c_description'], $L['c_direction']],
            array_map(fn ($r) => [$this->text($get($r, 'label')), $this->text($get($r, 'description')), $this->level($get($r, 'direction'), $L)], $list('trends')));

        $push($L['correlations'], ['', $L['c_correlation'], $L['c_strength']],
            array_map(fn ($r) => ['', $this->text($r), $this->level($get($r, 'strength'), $L)], $list('correlations')));

        $push($L['anomalies'], ['', $L['c_anomaly'], $L['c_severity']],
            array_map(fn ($r) => ['', $this->text($r), $this->level($get($r, 'severity'), $L)], $list('anomalies')));

        $push($L['risks'], ['', $L['c_risk'], $L['c_severity']],
            array_map(fn ($r) => ['', $this->text($r), $this->level($get($r, 'severity'), $L)], $list('risks')));

        $push($L['opportunities'], ['', $L['c_opportunity'], $L['c_impact']],
            array_map(fn ($r) => ['', $this->text($r), $this->level($get($r, 'potential_impact'), $L)], $list('opportunities')));

        $push($L['root_cause_analysis'], [$L['c_issue'], $L['c_cause'], ''],
            array_map(fn ($r) => [$this->text($get($r, 'issue')), $this->text($get($r, 'likely_cause')), ''], $list('root_cause_analysis')));

        $push($L['kpi_analysis'], [$L['c_kpi'], $L['c_analysis'], ''],
            array_map(fn ($r) => [$this->text($get($r, 'kpi')), $this->text($get($r, 'analysis')), ''], $list('kpi_analysis')));

        $push($L['recommendations'], ['', $L['c_recommendation'], ''],
            array_map(fn ($r) => ['', $this->text($r), ''], $list('recommendations')));

        $push($L['performance_recommendations'], ['', $L['c_perf'], ''],
            array_map(fn ($r) => ['', $this->text($r), ''], $list('performance_recommendations')));

        return $out;
    }

    // ------------------------------------------------------------------
    //  Writers
    // ------------------------------------------------------------------

    /**
     * PDF: جدول لكل قسم، بس الأعمدة اللي فيها بيانات فعلًا (مفيش عمود فاضي).
     *
     * @return array<int,array{title:string,header:string[],rows:array<int,array<int,string>>}>
     */
    private function pdfSections(array $sections): array
    {
        $out = [];
        foreach ($sections as $sec) {
            $keep = [];
            foreach ([0, 1, 2] as $i) {
                foreach ($sec['items'] as $item) {
                    if (($item[$i] ?? '') !== '') {
                        $keep[] = $i;
                        break;
                    }
                }
            }
            $out[] = [
                'title'  => $sec['title'],
                'header' => array_map(fn ($i) => $sec['columns'][$i], $keep),
                'rows'   => array_map(fn ($item) => array_map(fn ($i) => $item[$i], $keep), $sec['items']),
            ];
        }
        return $out;
    }

    /** docx / xlsx / csv / json: جدول مسطّح بأربع أعمدة. */
    private function writeFlat(string $format, string $path, string $title, array $sections, array $L): void
    {
        $header = [$L['section'], $L['item'], $L['details'], $L['level']];
        $rows = [];
        foreach ($sections as $sec) {
            foreach ($sec['items'] as $item) {
                $rows[] = [$sec['title'], $item[0], $item[1], $item[2]];
            }
        }
        ReportExportWriter::write($format, $header, $rows, $path, $title);
    }

    private function writeMarkdown(string $path, string $title, array $meta, array $sections): void
    {
        $md = "# {$title}\n\n";
        foreach ($meta as $k => $v) {
            $md .= "- **{$k}:** {$v}\n";
        }
        foreach ($sections as $sec) {
            $md .= "\n## {$sec['title']}\n\n";
            foreach ($sec['items'] as [$item, $details, $level]) {
                $line = $item !== '' ? "**{$item}** — {$details}" : $details;
                if ($level !== '') {
                    $line .= " _({$level})_";
                }
                // ملخص الـ executive بيتكتب فقرة، الباقي نقاط.
                $md .= !empty($sec['paragraph']) ? $line . "\n" : "- {$line}\n";
            }
        }
        if (file_put_contents($path, $md) === false) {
            throw new \RuntimeException('Could not write the AI Insights export file.');
        }
    }
}
